import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const SITE = {
  name: 'EDOX Logistics',
  phoneDisplay: '06 - 00 00 00 00',
  phone: '+31600000000',
  email: 'info@edoxlogistics.nl',
  instagram: 'https://instagram.com/edoxlogistics',
  linkedin: 'https://linkedin.com/company/edox-logistics',
  // Dit pad wordt vanuit de door Vite gebouwde CSS-bundel opgelost.
  heroImage: '../assets/images/edox-hero-truck.jpg', // Vervang later door een echte EDOX-truckfoto.
};

const translations = {
  nl: {
    locale: 'nl-NL', nav: ['Home','Voor opdrachtgevers','Voor chauffeurs','Diensten','Werkwijze','Offerte','Contact'],
    topbar: 'Transportoplossingen voor Nederland, Duitsland en België', quote: 'Offerte aanvragen', driverCta: 'Chauffeur aanmelden',
    heroTitle: 'Transportcapaciteit waar je op kunt bouwen.', heroText: 'Betrouwbaar transport en flexibele chauffeursdiensten voor bedrijven in Nederland, Duitsland, België en West-Europa. Duidelijke communicatie, sterke uitvoering en afspraak = afspraak.', heroDriver: 'Ik ben chauffeur',
    trustBadges: ['Afspraak = afspraak','CE-bestuurders','Nederland, Duitsland & België','Internationale chauffeurs'],
    clientKicker: 'Voor opdrachtgevers', clientTitle: 'Transportpartner voor bedrijven in West-Europa', clientText: 'EDOX Logistics ondersteunt opdrachtgevers met betrouwbare transportcapaciteit, chauffeursdiensten en logistieke oplossingen in Nederland, Duitsland, België en de rest van West-Europa.', clientBullets: ['Transportbedrijf Nederland','Zakelijk transport','Chauffeursdiensten','CE-bestuurders','Flexibele transportcapaciteit','Duidelijke communicatie'], clientCta: 'Vraag transportofferte aan',
    driverKicker: 'Voor chauffeurs', driverTitle: 'Werk zoeken als transportchauffeur?', driverText: 'Ben jij chauffeur of CE-bestuurder en sta je open voor werk via EDOX Logistics? Laat je gegevens achter. Wij nemen contact met je op zodra er passende mogelijkheden zijn.', driverRegions:'Wij verwelkomen internationale chauffeurs uit Europa en Centraal-Azië, waaronder Hongarije, Kazachstan en Oezbekistan.', driverReassure: 'EDOX Logistics neemt contact met je op wanneer er passende mogelijkheden zijn.',
    labels: { name:'Naam', email:'E-mail', phone:'Telefoonnummer', language:'Taalvoorkeur', country:'Land', license:'Rijbewijs', message:'Bericht', optional:'optioneel', company:'Bedrijfsnaam', contact:'Contactpersoon', street:'Straat + huisnummer', postcode:'Postcode', city:'Plaats', goods:'Soort goederen', weight:'Gewicht in kg', volume:'Volume in m³', notes:'Opmerkingen', dateLoad:'Laaddatum', dateUnload:'Losdatum', service:'Gewenste dienst', privacy:'Ik ga akkoord dat EDOX Logistics mijn gegevens gebruikt om contact met mij op te nemen.' },
    submitDriver:'Laat je gegevens achter', driverSuccess:'Bedankt voor je aanmelding. EDOX Logistics neemt contact met je op wanneer er een passende mogelijkheid is.',
    trustKicker:'Waarom EDOX', trustTitle:'Sterk in uitvoering. Duidelijk in afspraken.', trust: [['Op tijd','Planning en uitvoering volgens afspraak.'],['Sterke chauffeurs','Betrouwbare CE-bestuurders die begrijpen wat transport vraagt.'],['Heldere communicatie','Korte lijnen, duidelijke afspraken en snelle terugkoppeling.'],['Internationaal inzetbaar','Focus op Nederland, Duitsland, België en internationale chauffeurs.']],
    servicesKicker:'Onze diensten', servicesTitle:'Diensten van EDOX Logistics', servicesIntro:'Praktische transportoplossingen voor opdrachtgevers die continuïteit, kwaliteit en heldere communicatie verwachten.', services:[['Transportbedrijf Nederland','Voor zakelijke klanten die zoeken naar betrouwbare transportcapaciteit in Nederland.'],['Internationaal transport','Transportoplossingen en ondersteuning in Nederland, Duitsland, België en West-Europa.'],['CE-bestuurders','Betrouwbare CE-bestuurders voor tijdelijke of structurele inzet.'],['Chauffeursdiensten','Flexibele ondersteuning voor logistieke bedrijven en transportopdrachten.'],['Zakelijk transport','Voor bedrijven die waarde hechten aan timing, zorgvuldigheid en betrouwbaarheid.'],['Logistieke ondersteuning','Extra capaciteit bij drukte, personeelstekort of piekmomenten.']],
    problemKicker:'Betrouwbaarheid als basis', problemTitle:'Transport valt of staat met betrouwbaarheid.', problemLabel:'Het probleem', problemHead:'Als de planning begint te schuiven', problemText:'Veel bedrijven lopen vast door vertragingen, slechte communicatie en transportpartners die afspraken niet nakomen. In logistiek kan één vertraagde rit direct gevolgen hebben voor planning, klanttevredenheid en kosten.', solutionLabel:'De EDOX-aanpak', solutionHead:'Rust door sterke uitvoering', solutionText:'EDOX Logistics biedt betrouwbare transportondersteuning met duidelijke afspraken, sterke chauffeurs en consistente uitvoering. Geen loze beloftes, maar doen wat is afgesproken.', solutionBullets:['Minder ruis in de planning','Betere betrouwbaarheid','Sneller schakelen','Duidelijke terugkoppeling','Sterke internationale chauffeursbasis'],
    processKicker:'Werkwijze', processTitle:'Zo werkt EDOX Logistics', steps:[['Aanvraag','Een opdrachtgever vraagt transportcapaciteit of chauffeursdiensten aan.'],['Afstemming','We bespreken planning, land, type goederen, inzet en specifieke eisen.'],['Match & planning','We stemmen de juiste capaciteit of chauffeur af op de opdracht.'],['Uitvoering','De opdracht wordt professioneel uitgevoerd volgens afspraak.'],['Terugkoppeling','Heldere communicatie voor, tijdens en na de opdracht.']],
    quoteKicker:'Voor opdrachtgevers', quoteTitle:'Vraag een transportofferte aan', quoteIntro:'Vul je gegevens in en EDOX Logistics neemt contact op voor een passende transportoplossing.', groups:['Bedrijfsgegevens','Adres opdrachtgever','Transportgegevens','Laadadres','Losadres'], submitQuote:'Offerte versturen', quoteSuccess:'Bedankt. Je offerteaanvraag is ontvangen. EDOX Logistics neemt contact met je op.',
    socialKicker:'Blijf op de hoogte', socialTitle:'Volg EDOX Logistics', socialText:'Volg EDOX Logistics op Instagram en LinkedIn voor updates, vacatures, transportinzichten en een kijkje achter de schermen.', socialCards:[['FAST • STRONG • TRUSTED','Sterke uitvoering en betrouwbare transportcapaciteit.'],['Chauffeurs gezocht','Internationale CE-bestuurders kunnen zich direct aanmelden.'],['Transportcapaciteit nodig?','Bespreek jouw planning met EDOX Logistics.']], follow:'Volgen',
    aboutKicker:'Over EDOX', aboutTitle:'Gebouwd op kracht, vertrouwen en betrouwbaarheid.', aboutText:'EDOX Logistics is een ambitieus transportbedrijf met een sterke internationale blik. Wij geloven dat transport draait om vertrouwen, duidelijke communicatie en het nakomen van afspraken. Met focus op opdrachtgevers in West-Europa en internationale chauffeurs bouwen we aan een sterk en betrouwbaar logistiek netwerk.',
    seoTitle:'Transportbedrijf Nederland voor betrouwbare logistieke ondersteuning', seoText:'EDOX Logistics is een transportbedrijf voor zakelijke klanten die betrouwbare transportcapaciteit zoeken in Nederland, Duitsland en België. Wij ondersteunen bedrijven met CE-bestuurders, chauffeursdiensten, zakelijk transport en logistieke ondersteuning. Dankzij duidelijke communicatie en een afspraak-is-afspraakmentaliteit helpt EDOX Logistics opdrachtgevers in West-Europa met sterke en betrouwbare transportoplossingen en internationale chauffeurs.',
    ctaTitle:'Transportcapaciteit of chauffeurs nodig?', ctaText:'Neem contact op met EDOX Logistics en ontdek hoe wij jouw planning kunnen ondersteunen met betrouwbare chauffeurs en duidelijke afspraken.',
    contactKicker:'Direct contact', contactTitle:'Korte lijnen. Snel antwoord.', workArea:'Nederland, Duitsland, België en West-Europa', forDrivers:'Voor chauffeurs', forDriversText:'Laat je gegevens achter via het chauffeur-formulier.', forClients:'Voor opdrachtgevers', forClientsText:'Vraag direct een offerte aan via het offerteformulier.',
    footerText:'Betrouwbare transportcapaciteit voor bedrijven in West-Europa.', companyData:'Bedrijfsgegevens', quickLinks:'Snel naar', privacy:'Privacyverklaring', terms:'Algemene voorwaarden', rights:'Alle rechten voorbehouden.'
  },
  en: {
    locale:'en', nav:['Home','For clients','For drivers','Services','Process','Quote','Contact'], topbar:'Transport solutions for the Netherlands, Germany and Belgium', quote:'Request a quote', driverCta:'Driver application',
    heroTitle:'Transport capacity you can build on.', heroText:'Reliable transport and flexible driver services for companies in the Netherlands, Germany, Belgium and Western Europe. Clear communication, strong execution and promises kept.', heroDriver:'I am a driver', trustBadges:['Promises kept','CE drivers','Netherlands, Germany & Belgium','International drivers'],
    clientKicker:'For clients', clientTitle:'Transport partner for companies in Western Europe', clientText:'EDOX Logistics supports clients with reliable transport capacity, driver services and logistics solutions across the Netherlands, Germany, Belgium and Western Europe.', clientBullets:['Transport company Netherlands','Business transport','Driver services','CE drivers','Flexible capacity','Clear communication'], clientCta:'Request a transport quote',
    driverKicker:'For drivers', driverTitle:'Looking for work as a transport driver?', driverText:'Are you a driver or CE-qualified driver open to opportunities through EDOX Logistics? Leave your details and we will contact you when a suitable position becomes available.', driverRegions:'We welcome international drivers from Europe and Central Asia, including Hungary, Kazakhstan and Uzbekistan.', driverReassure:'EDOX Logistics will contact you when a suitable opportunity becomes available.',
    labels:{name:'Name',email:'Email',phone:'Phone number',language:'Preferred language',country:'Country',license:'Driving licence',message:'Message',optional:'optional',company:'Company name',contact:'Contact person',street:'Street + number',postcode:'Postal code',city:'City',goods:'Type of goods',weight:'Weight in kg',volume:'Volume in m³',notes:'Notes',dateLoad:'Loading date',dateUnload:'Unloading date',service:'Required service',privacy:'I agree that EDOX Logistics may use my data to contact me.'}, submitDriver:'Leave your details', driverSuccess:'Thank you. EDOX Logistics will contact you when a suitable opportunity becomes available.',
    trustKicker:'Why EDOX',trustTitle:'Strong execution. Clear agreements.',trust:[['On time','Planning and delivery according to agreement.'],['Strong drivers','Reliable CE drivers who understand transport.'],['Clear communication','Short lines, clear agreements and fast feedback.'],['International reach','Focused on Western Europe and international drivers.']],
    servicesKicker:'Our services',servicesTitle:'EDOX Logistics services',servicesIntro:'Practical transport solutions for clients who expect continuity, quality and clear communication.',services:[['Transport company Netherlands','Reliable transport capacity for business clients in the Netherlands.'],['International transport','Solutions across the Netherlands, Germany, Belgium and Western Europe.'],['CE drivers','Reliable CE drivers for temporary or structural deployment.'],['Driver services','Flexible support for logistics companies and transport operations.'],['Business transport','For companies that value timing, care and reliability.'],['Logistics support','Extra capacity during peaks or staff shortages.']],
    problemKicker:'Reliability first',problemTitle:'Transport depends on reliability.',problemLabel:'The problem',problemHead:'When planning starts to slip',problemText:'Delays, poor communication and broken promises can directly affect planning, customer satisfaction and costs.',solutionLabel:'The EDOX approach',solutionHead:'Control through strong execution',solutionText:'EDOX Logistics provides clear agreements, strong drivers and consistent execution. No empty promises: we do what we agreed.',solutionBullets:['Less planning noise','Better reliability','Faster response','Clear feedback','Strong international driver base'],
    processKicker:'Our process',processTitle:'How EDOX Logistics works',steps:[['Request','A client requests transport capacity or driver services.'],['Alignment','We discuss planning, country, goods and requirements.'],['Match & planning','We match the right capacity or driver to the assignment.'],['Execution','The assignment is delivered professionally.'],['Feedback','Clear communication before, during and after.']],
    quoteKicker:'For clients',quoteTitle:'Request a transport quote',quoteIntro:'Submit your details and EDOX Logistics will contact you with a suitable solution.',groups:['Company details','Client address','Transport details','Loading address','Delivery address'],submitQuote:'Send quote request',quoteSuccess:'Thank you. Your request has been received. EDOX Logistics will contact you.',
    socialKicker:'Stay informed',socialTitle:'Follow EDOX Logistics',socialText:'Follow us on Instagram and LinkedIn for updates, vacancies and transport insights.',socialCards:[['FAST • STRONG • TRUSTED','Strong execution and reliable capacity.'],['Drivers wanted','International CE drivers can apply directly.'],['Need transport capacity?','Discuss your planning with EDOX Logistics.']],follow:'Follow',
    aboutKicker:'About EDOX',aboutTitle:'Built on strength, trust and reliability.',aboutText:'EDOX Logistics is an ambitious transport company with an international outlook. We believe transport is built on trust, clear communication and keeping agreements.',seoTitle:'Transport company Netherlands for reliable logistics support',seoText:'EDOX Logistics provides reliable transport capacity in the Netherlands, Germany and Belgium with CE drivers, driver services, business transport and logistics support for Western Europe.',ctaTitle:'Need transport capacity or drivers?',ctaText:'Contact EDOX Logistics to discuss reliable drivers and clear agreements.',contactKicker:'Direct contact',contactTitle:'Short lines. Fast response.',workArea:'Netherlands, Germany, Belgium and Western Europe',forDrivers:'For drivers',forDriversText:'Leave your details through the driver form.',forClients:'For clients',forClientsText:'Request a quote through the quote form.',footerText:'Reliable transport capacity for Western Europe.',companyData:'Company details',quickLinks:'Quick links',privacy:'Privacy statement',terms:'Terms and conditions',rights:'All rights reserved.'
  },
  ru: {
    locale:'ru', nav:['Главная','Заказчикам','Водителям','Услуги','Как мы работаем','Заявка','Контакты'], topbar:'Транспортные решения в Нидерландах, Германии и Бельгии', quote:'Запросить предложение', driverCta:'Анкета водителя',
    heroTitle:'Транспортные мощности, на которые можно положиться.', heroText:'Надёжные перевозки и гибкие услуги водителей для компаний в Нидерландах, Германии, Бельгии и Западной Европе. Чёткая связь, сильное исполнение и соблюдение договорённостей.', heroDriver:'Я водитель', trustBadges:['Договорённости соблюдаются','Водители CE','Нидерланды, Германия и Бельгия','Международные водители'],
    clientKicker:'Заказчикам',clientTitle:'Транспортный партнёр для компаний Западной Европы',clientText:'EDOX Logistics предлагает надёжные транспортные мощности, услуги водителей и логистические решения в Нидерландах, Германии, Бельгии и Западной Европе.',clientBullets:['Перевозки в Нидерландах','Корпоративный транспорт','Услуги водителей','Водители CE','Гибкие мощности','Чёткая коммуникация'],clientCta:'Запросить расчёт перевозки',
    driverKicker:'Водителям',driverTitle:'Ищете работу водителем?',driverText:'Вы водитель или обладатель категории CE и рассматриваете работу через EDOX Logistics? Оставьте контакты, и мы свяжемся с вами при появлении подходящей возможности.',driverRegions:'Мы приглашаем международных водителей из Европы и Центральной Азии, включая Венгрию, Казахстан и Узбекистан.',driverReassure:'EDOX Logistics свяжется с вами, когда появится подходящая возможность.',
    labels:{name:'Имя',email:'Эл. почта',phone:'Телефон',language:'Предпочтительный язык',country:'Страна',license:'Категория прав',message:'Сообщение',optional:'необязательно',company:'Компания',contact:'Контактное лицо',street:'Улица и номер',postcode:'Индекс',city:'Город',goods:'Тип груза',weight:'Вес, кг',volume:'Объём, м³',notes:'Примечания',dateLoad:'Дата загрузки',dateUnload:'Дата выгрузки',service:'Необходимая услуга',privacy:'Я согласен на использование моих данных EDOX Logistics для связи со мной.'},submitDriver:'Оставить контакты',driverSuccess:'Спасибо. EDOX Logistics свяжется с вами при появлении подходящей возможности.',
    trustKicker:'Почему EDOX',trustTitle:'Сильное исполнение. Чёткие договорённости.',trust:[['Вовремя','Планирование и выполнение по договорённости.'],['Сильные водители','Надёжные водители CE, понимающие транспорт.'],['Чёткая связь','Прямой контакт и быстрая обратная связь.'],['Международный охват','Западная Европа и международные водители.']],
    servicesKicker:'Наши услуги',servicesTitle:'Услуги EDOX Logistics',servicesIntro:'Практичные транспортные решения для компаний, которым важны стабильность, качество и связь.',services:[['Перевозки в Нидерландах','Надёжные мощности для корпоративных клиентов.'],['Международные перевозки','Нидерланды, Германия, Бельгия и Западная Европа.'],['Водители CE','Временное или постоянное привлечение водителей CE.'],['Услуги водителей','Гибкая поддержка логистических компаний.'],['Корпоративный транспорт','Точность, бережность и надёжность.'],['Логистическая поддержка','Дополнительные мощности в периоды нагрузки.']],
    problemKicker:'Надёжность прежде всего',problemTitle:'Транспорт зависит от надёжности.',problemLabel:'Проблема',problemHead:'Когда график начинает сдвигаться',problemText:'Задержки, слабая связь и невыполненные обещания влияют на планирование, клиентов и расходы.',solutionLabel:'Подход EDOX',solutionHead:'Контроль благодаря сильному исполнению',solutionText:'EDOX Logistics предлагает чёткие договорённости, сильных водителей и стабильное выполнение.',solutionBullets:['Меньше сбоев','Больше надёжности','Быстрая реакция','Чёткая обратная связь','Международная база водителей'],
    processKicker:'Процесс',processTitle:'Как работает EDOX Logistics',steps:[['Запрос','Заказчик запрашивает транспорт или водителя.'],['Согласование','Обсуждаем график, страну, груз и требования.'],['Подбор и планирование','Подбираем мощности или водителя.'],['Выполнение','Профессионально выполняем заказ.'],['Обратная связь','Связь до, во время и после заказа.']],
    quoteKicker:'Заказчикам',quoteTitle:'Запросить транспортное предложение',quoteIntro:'Оставьте данные, и EDOX Logistics предложит подходящее решение.',groups:['Данные компании','Адрес заказчика','Данные груза','Адрес загрузки','Адрес выгрузки'],submitQuote:'Отправить запрос',quoteSuccess:'Спасибо. Ваш запрос получен. EDOX Logistics свяжется с вами.',
    socialKicker:'Будьте в курсе',socialTitle:'Следите за EDOX Logistics',socialText:'Новости, вакансии и транспортные материалы в Instagram и LinkedIn.',socialCards:[['FAST • STRONG • TRUSTED','Сильное исполнение и надёжные мощности.'],['Ищем водителей','Международные водители CE могут оставить заявку.'],['Нужен транспорт?','Обсудите планирование с EDOX Logistics.']],follow:'Подписаться',
    aboutKicker:'О компании',aboutTitle:'Сила, доверие и надёжность.',aboutText:'EDOX Logistics — амбициозная транспортная компания с международным взглядом. Мы строим работу на доверии, чёткой связи и соблюдении договорённостей.',seoTitle:'Транспортная компания в Нидерландах',seoText:'EDOX Logistics предоставляет транспортные мощности, водителей CE, корпоративные перевозки и логистическую поддержку в Нидерландах, Германии, Бельгии и Западной Европе.',ctaTitle:'Нужен транспорт или водители?',ctaText:'Свяжитесь с EDOX Logistics для надёжного решения.',contactKicker:'Контакты',contactTitle:'Прямая связь. Быстрый ответ.',workArea:'Нидерланды, Германия, Бельгия и Западная Европа',forDrivers:'Водителям',forDriversText:'Оставьте контакты в анкете водителя.',forClients:'Заказчикам',forClientsText:'Запросите предложение через форму.',footerText:'Надёжные транспортные мощности в Западной Европе.',companyData:'Реквизиты',quickLinks:'Ссылки',privacy:'Конфиденциальность',terms:'Условия',rights:'Все права защищены.'
  }
};

const serviceValues = ['Transport Nederland','Internationaal transport','CE-bestuurder','Chauffeursdienst','Logistieke ondersteuning','Anders'];
const iconPaths = {
  phone:<path d="M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-4-1-1 2c-4-1.5-8.5-6-10-10l2-1-1-4z"/>, mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></>, arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></>, check:<path d="M5 12l4 4L19 6"/>, menu:<path d="M4 7h16M4 12h16M4 17h16"/>, close:<path d="M6 6l12 12M18 6L6 18"/>, truck:<><path d="M3 5h11v11H3zM14 9h4l3 4v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>, driver:<><circle cx="12" cy="8" r="3"/><path d="M6 20v-2a6 6 0 0 1 12 0v2M4 4h16"/></>, clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, message:<><path d="M5 17l-2 4 5-2h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H6a3 3 0 0 0-3 3v7a3 3 0 0 0 2 3z"/><path d="M8 9h8M8 13h5"/></>, globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3.4 3 14.6 0 18M12 3c-3 3.4-3 14.6 0 18"/></>, route:<><circle cx="5" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M7 6h5a3 3 0 0 1 0 6H9a3 3 0 0 0 0 6h8"/></>, box:<><path d="M4 7l8-4 8 4-8 4-8-4zM4 7v10l8 4 8-4V7M12 11v10"/></>, building:<><path d="M4 21V5l8-3v19M12 8h8v13M7 7h2M7 11h2M7 15h2M15 12h2M15 16h2M2 21h20"/></>, instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".5" fill="currentColor"/></>, linkedin:<><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 10v7M8 7v.01M12 17v-4a3 3 0 0 1 6 0v4M12 10v7"/></>
};
const Icon=({name,size=21})=><svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{iconPaths[name]}</svg>;
const Container=({children,className=''})=><div className={`container ${className}`}>{children}</div>;
const Brand=({light=false})=><a href="#home" className={`brand ${light?'brand-light':''}`} aria-label="EDOX Logistics home"><span className="brand-star" aria-hidden="true">✦</span><span className="brand-word"><strong>EDOX</strong><small>LOGISTICS</small></span></a>;
const Button=({href,children,secondary=false})=><a className={`button ${secondary?'button-secondary':'button-primary'}`} href={href}>{children}<Icon name="arrow" size={17}/></a>;

function Topbar({t,lang,setLang}){return <div className="topbar"><Container className="topbar-inner"><div className="top-contact"><a href={`tel:${SITE.phone}`}><Icon name="phone" size={14}/>{SITE.phoneDisplay}</a><a href={`mailto:${SITE.email}`}><Icon name="mail" size={14}/>{SITE.email}</a></div><span className="top-message">{t.topbar}</span><div className="top-actions"><a href={SITE.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Icon name="instagram" size={15}/></a><a href={SITE.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Icon name="linkedin" size={15}/></a><div className="language-switch" aria-label="Language selector">{['nl','en','ru'].map(x=><button key={x} className={lang===x?'active':''} onClick={()=>setLang(x)} lang={x}>{x.toUpperCase()}</button>)}</div></div></Container></div>}
function Header({t}){const[open,setOpen]=useState(false);const ids=['home','opdrachtgevers','chauffeurs','diensten','werkwijze','offerte','contact'];return <header className="header"><Container className="header-inner"><Brand/><nav id="main-nav" className={open?'nav open':'nav'} aria-label="Main navigation">{t.nav.map((x,i)=><a key={x} href={`#${ids[i]}`} onClick={()=>setOpen(false)}>{x}</a>)}<div className="mobile-nav-ctas"><Button href="#offerte">{t.quote}</Button><Button href="#chauffeurs" secondary>{t.driverCta}</Button></div></nav><div className="header-ctas"><Button href="#offerte">{t.quote}</Button><Button href="#chauffeurs" secondary>{t.driverCta}</Button></div><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="main-nav" aria-label={open?'Close menu':'Open menu'}><Icon name={open?'close':'menu'}/></button></Container></header>}
function SectionHead({kicker,title,text,light=false,center=false}){return <div className={`section-head ${light?'light':''} ${center?'center':''}`}><span className="kicker">{kicker}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}

function Hero({t}){return <section className="hero" id="home" style={{'--hero-image':`url(${SITE.heroImage})`}}><div className="hero-overlay"/><div className="hero-lines"/><Container className="hero-content"><div className="hero-copy"><div className="hero-brandline"><span>EDOX LOGISTICS</span><i/></div><h1>{t.heroTitle}</h1><strong className="slogan">FAST <b>•</b> STRONG <b>•</b> TRUSTED</strong><p>{t.heroText}</p><div className="hero-buttons"><Button href="#offerte">{t.quote}</Button><Button href="#chauffeurs" secondary>{t.heroDriver}</Button></div><div className="hero-badges">{t.trustBadges.map((x,i)=><span key={x}><Icon name={['check','driver','route','globe'][i]} size={16}/>{x}</span>)}</div></div></Container><div className="hero-route-label"><span>NL</span><i/><span>DE</span><i/><span>BE</span><i/><span>EU</span></div></section>}

function Clients({t}){return <section className="section clients" id="opdrachtgevers"><Container className="split"><div><SectionHead kicker={t.clientKicker} title={t.clientTitle} text={t.clientText}/><div className="check-grid">{t.clientBullets.map(x=><span key={x}><Icon name="check" size={15}/>{x}</span>)}</div><Button href="#offerte">{t.clientCta}</Button></div><div className="image-panel client-image" role="img" aria-label="EDOX Logistics transport network in Western Europe"><span className="image-label">WESTERN EUROPE</span><div className="route-map"><b>NL</b><i/><b>DE</b><i/><b>BE</b></div><div className="image-stat"><strong>3</strong><span>core<br/>markets</span></div></div></Container></section>}

function DriverForm({t}){const[done,setDone]=useState(false);const submit=e=>{e.preventDefault();setDone(true);e.currentTarget.reset();};return <form className="compact-form" onSubmit={submit}>{done&&<div className="success" role="status"><Icon name="check"/>{t.driverSuccess}</div>}<div className="form-row three"><Field label={`${t.labels.name} *`} name="driverName" required/><Field type="email" label={`${t.labels.email} *`} name="driverEmail" required/><Field type="tel" label={`${t.labels.phone} *`} name="driverPhone" required/></div><div className="form-row three"><Select label={`${t.labels.language} (${t.labels.optional})`} name="language" options={['Nederlands','English','Русский']}/><Field label={`${t.labels.country} (${t.labels.optional})`} name="country"/><Select label={`${t.labels.license} (${t.labels.optional})`} name="license" options={['CE','C','Anders / Other']}/></div><Field textarea label={`${t.labels.message} (${t.labels.optional})`} name="driverMessage"/><button type="submit" className="button button-primary full">{t.submitDriver}<Icon name="arrow" size={17}/></button>{/* KOPPELPUNT CHAUFFEUR: vervang submit-handler door Netlify Forms, Formspree, EmailJS of API. */}</form>}
function Drivers({t}){return <section className="section drivers" id="chauffeurs"><Container><div className="driver-shell"><div className="driver-copy"><SectionHead light kicker={t.driverKicker} title={t.driverTitle} text={t.driverText}/><p className="driver-regions"><Icon name="globe" size={17}/>{t.driverRegions}</p><div className="driver-photo-slot" role="img" aria-label="International CE driver at an EDOX Logistics truck"><span>// EDOX DRIVER NETWORK</span></div><p className="reassure"><Icon name="check" size={16}/>{t.driverReassure}</p></div><DriverForm t={t}/></div></Container></section>}

function Trust({t}){const icons=['clock','driver','message','globe'];return <section className="section trust"><Container><SectionHead center kicker={t.trustKicker} title={t.trustTitle}/><div className="trust-grid">{t.trust.map((x,i)=><article key={x[0]} className="trust-card"><span className="number">0{i+1}</span><div className="icon"><Icon name={icons[i]}/></div><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></Container></section>}
function Services({t}){const icons=['truck','globe','driver','route','building','box'];return <section className="section services" id="diensten"><Container><SectionHead center kicker={t.servicesKicker} title={t.servicesTitle} text={t.servicesIntro}/><div className="services-grid">{t.services.map((x,i)=><article className="service-card" key={x[0]}><div className="service-icon"><Icon name={icons[i]} size={24}/></div><small>0{i+1}</small><h3>{x[0]}</h3><p>{x[1]}</p><a href="#offerte">{t.quote}<Icon name="arrow" size={16}/></a></article>)}</div></Container></section>}
function Problem({t}){return <section className="section problem"><Container><SectionHead kicker={t.problemKicker} title={t.problemTitle}/><div className="problem-grid"><article className="problem-card problem-dark"><span>{t.problemLabel}</span><h3>{t.problemHead}</h3><p>{t.problemText}</p><div className="delay-bars"><i/><i/><i/><i/></div></article><article className="problem-card solution"><span>{t.solutionLabel}</span><h3>{t.solutionHead}</h3><p>{t.solutionText}</p><ul>{t.solutionBullets.map(x=><li key={x}><Icon name="check" size={15}/>{x}</li>)}</ul></article><div className="problem-photo" role="img" aria-label="EDOX Logistics truck and route planning"><span>EDOX / ON THE ROAD</span></div></div></Container></section>}
function Process({t}){return <section className="section process" id="werkwijze"><Container><SectionHead light kicker={t.processKicker} title={t.processTitle}/><div className="steps">{t.steps.map((x,i)=><article key={x[0]}><div className="step-no">0{i+1}</div><i/><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></Container></section>}

function Field({label,name,type='text',required=false,textarea=false}){return <label>{label}{textarea?<textarea name={name} rows="3"/>:<input name={name} type={type} required={required}/>}</label>}
function Select({label,name,options,required=false}){return <label>{label}<select name={name} required={required}><option value="">—</option>{options.map(x=><option value={x} key={x}>{x}</option>)}</select></label>}
function AddressFields({t,prefix,dateLabel}){return <><div className="form-row">{dateLabel&&<Field type="date" label={dateLabel} name={`${prefix}Date`}/>}<Field label={t.labels.country} name={`${prefix}Country`}/></div><Field label={t.labels.street} name={`${prefix}Street`}/><div className="form-row"><Field label={t.labels.postcode} name={`${prefix}Postcode`}/><Field label={t.labels.city} name={`${prefix}City`}/></div></>}
function QuoteForm({t}){const[done,setDone]=useState(false);const submit=e=>{e.preventDefault();setDone(true);e.currentTarget.reset();};return <form className="quote-form" onSubmit={submit}>{done&&<div className="success" role="status"><Icon name="check"/>{t.quoteSuccess}</div>}<fieldset><legend><span>01</span>{t.groups[0]}</legend><div className="form-row"><Field label={`${t.labels.company} *`} name="company" required/><Field label={`${t.labels.contact} *`} name="contact" required/></div><div className="form-row"><Field type="email" label={`${t.labels.email} *`} name="email" required/><Field type="tel" label={`${t.labels.phone} *`} name="phone" required/></div></fieldset><fieldset><legend><span>02</span>{t.groups[1]}</legend><AddressFields t={t} prefix="client"/></fieldset><fieldset><legend><span>03</span>{t.groups[2]}</legend><div className="form-row three"><Field label={`${t.labels.goods} *`} name="goods" required/><Field type="number" label={t.labels.weight} name="weight"/><Field type="number" label={t.labels.volume} name="volume"/></div><Select label={`${t.labels.service} *`} name="service" options={serviceValues} required/><Field textarea label={t.labels.notes} name="notes"/></fieldset><div className="address-pair"><fieldset><legend><span>04</span>{t.groups[3]}</legend><AddressFields t={t} prefix="load" dateLabel={t.labels.dateLoad}/></fieldset><fieldset><legend><span>05</span>{t.groups[4]}</legend><AddressFields t={t} prefix="unload" dateLabel={t.labels.dateUnload}/></fieldset></div><label className="privacy-check"><input type="checkbox" required/><span>{t.labels.privacy}</span></label><button type="submit" className="button button-primary quote-submit">{t.submitQuote}<Icon name="arrow" size={18}/></button>{/* KOPPELPUNT OFFERTE: voeg action/endpoint toe voor Netlify, Formspree, EmailJS of backend API. */}</form>}
function Quote({t}){return <section className="section quote" id="offerte"><Container><SectionHead kicker={t.quoteKicker} title={t.quoteTitle} text={t.quoteIntro}/><QuoteForm t={t}/></Container></section>}

function Social({t}){return <section className="section social"><Container><SectionHead center kicker={t.socialKicker} title={t.socialTitle} text={t.socialText}/><div className="social-grid">{t.socialCards.map((x,i)=><article key={x[0]} className={`social-card social-${i+1}`}><span>{['01 / BRAND','02 / DRIVERS','03 / CAPACITY'][i]}</span><div className="social-symbol">{['✦','CE','→'][i]}</div><h3>{x[0]}</h3><p>{x[1]}</p><a href={i===1?'#chauffeurs':'#offerte'}>{i===1?t.driverCta:t.quote}<Icon name="arrow" size={15}/></a></article>)}</div><div className="social-links"><a href={SITE.instagram} target="_blank" rel="noreferrer"><Icon name="instagram"/>Instagram</a><a href={SITE.linkedin} target="_blank" rel="noreferrer"><Icon name="linkedin"/>LinkedIn</a></div></Container></section>}
function About({t}){return <section className="section about"><Container className="about-grid"><div className="about-photo" role="img" aria-label="EDOX Logistics team, driver and truck placeholder"><span>// TEAM / OWNER / TRUCK</span><div className="about-mark">E</div></div><div><SectionHead kicker={t.aboutKicker} title={t.aboutTitle} text={t.aboutText}/><strong className="slogan dark">FAST <b>•</b> STRONG <b>•</b> TRUSTED</strong><div className="values">{['FAST','STRONG','TRUSTED'].map((x,i)=><span key={x}><small>0{i+1}</small>{x}</span>)}</div></div></Container></section>}
function Seo({t}){return <section className="seo"><Container><div className="seo-content"><span><Icon name="route"/></span><div><h2>{t.seoTitle}</h2><p>{t.seoText}</p></div></div></Container></section>}
function CTA({t}){return <section className="cta"><div className="cta-lines"/><Container><div><span className="kicker">EDOX LOGISTICS</span><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p></div><div><Button href="#offerte">{t.quote}</Button><Button href="#chauffeurs" secondary>{t.driverCta}</Button></div></Container></section>}
function Contact({t}){return <section className="section contact" id="contact"><Container><SectionHead center kicker={t.contactKicker} title={t.contactTitle}/><div className="contact-grid"><a href={`tel:${SITE.phone}`}><span><Icon name="phone"/></span><small>{t.labels.phone}</small><strong>{SITE.phoneDisplay}</strong></a><a href={`mailto:${SITE.email}`}><span><Icon name="mail"/></span><small>{t.labels.email}</small><strong>{SITE.email}</strong></a><div><span><Icon name="globe"/></span><small>WORK AREA</small><strong>{t.workArea}</strong></div></div><div className="contact-paths"><a href="#chauffeurs"><b>{t.forDrivers}</b><span>{t.forDriversText}</span><Icon name="arrow"/></a><a href="#offerte"><b>{t.forClients}</b><span>{t.forClientsText}</span><Icon name="arrow"/></a></div></Container></section>}
function Footer({t}){return <footer><Container><div className="footer-grid"><div><Brand light/><p>{t.footerText}</p><strong className="slogan">FAST • STRONG • TRUSTED</strong></div><div><h3>{t.contactKicker}</h3><a href={`tel:${SITE.phone}`}>{SITE.phoneDisplay}</a><a href={`mailto:${SITE.email}`}>{SITE.email}</a><span>{t.workArea}</span></div><div><h3>{t.companyData}</h3><span>KvK: 00000000</span><span>BTW: NL000000000B00</span><span>Vestigingsplaats, Nederland</span></div><div><h3>Social</h3><a href={SITE.instagram} target="_blank" rel="noreferrer">Instagram</a><a href={SITE.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="#contact">{t.nav[6]}</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} EDOX Logistics. {t.rights}</span><div><a href="#">{t.privacy}</a><a href="#">{t.terms}</a></div></div></Container></footer>}

function StructuredData(){useEffect(()=>{const script=document.createElement('script');script.type='application/ld+json';script.id='edox-structured-data';script.text=JSON.stringify({'@context':'https://schema.org','@type':['Organization','LocalBusiness'],'additionalType':'https://schema.org/TransportBusiness',name:SITE.name,url:'https://arixconnect.github.io/logistiek/',email:SITE.email,telephone:SITE.phone,address:{'@type':'PostalAddress',addressCountry:'NL'},areaServed:['Netherlands','Germany','Belgium','Western Europe'],sameAs:[SITE.instagram,SITE.linkedin],contactPoint:{'@type':'ContactPoint',telephone:SITE.phone,email:SITE.email,contactType:'sales',availableLanguage:['Dutch','English','Russian']}});document.head.appendChild(script);return()=>script.remove();},[]);return null}
function App(){const initial=(()=>{const query=new URLSearchParams(location.search).get('lang');return ['nl','en','ru'].includes(query)?query:'nl';})();const[lang,setLangState]=useState(initial);const t=translations[lang];const setLang=x=>{setLangState(x);const url=new URL(location.href);x==='nl'?url.searchParams.delete('lang'):url.searchParams.set('lang',x);history.replaceState({},'',url);};useEffect(()=>{document.documentElement.lang=t.locale;document.title=lang==='nl'?'EDOX Logistics | Transportbedrijf Nederland & CE-bestuurders':lang==='en'?'EDOX Logistics | Transport company & CE drivers':'EDOX Logistics | Транспорт и водители CE';document.querySelector('meta[name="description"]')?.setAttribute('content',lang==='nl'?'EDOX Logistics is een transportbedrijf voor Nederland, Duitsland en België. Betrouwbare CE-bestuurders, chauffeursdiensten en transportcapaciteit. FAST • STRONG • TRUSTED.':t.heroText);},[lang,t]);return <><StructuredData/><Topbar t={t} lang={lang} setLang={setLang}/><Header t={t}/><main><Hero t={t}/><Clients t={t}/><Drivers t={t}/><Trust t={t}/><Services t={t}/><Problem t={t}/><Process t={t}/><Quote t={t}/><Social t={t}/><About t={t}/><Seo t={t}/><CTA t={t}/><Contact t={t}/></main><Footer t={t}/></>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
